version: "3.9"
services:
#######
# Business Partner 1
#######
  bpa1:
    image: ghcr.io/hyperledger-labs/business-partner-agent:local
    build:
      context: ..
      dockerfile: Dockerfile

#######
# Business Partner 2 (only started with "--profile second_bpa")
#######
  bpa2:
    image: ghcr.io/hyperledger-labs/business-partner-agent:local
    build:
      context: ..
      dockerfile: Dockerfile

  #######
  # Business Partner 3 (only started with "--profile third_bpa")
  #######
  bpa3:
    image: ghcr.io/hyperledger-labs/business-partner-agent:local
    build:
      context: ..
      dockerfile: Dockerfile
